#!/bin/sh
python3 submission_ensemble_given_test_label_stage2_sub1.py 0
python3 submission_ensemble_given_test_label_stage2_sub1.py 1
python3 submission_ensemble_given_test_label_stage2_sub1.py 2
python3 submission_ensemble_given_test_label_stage2_sub1.py 3
python3 submission_ensemble_given_test_label_stage2_sub1.py 4
python3 submission_ensemble_given_test_label_stage2_sub1.py 5
python3 submission_ensemble_given_test_label_stage2_sub1.py 6