#!/bin/sh
python3 submission_ensemble_given_test_label_stage2_sub1.py 15
python3 submission_ensemble_given_test_label_stage2_sub1.py 16
python3 submission_ensemble_given_test_label_stage2_sub1.py 17
python3 submission_ensemble_given_test_label_stage2_sub1.py 18
python3 submission_ensemble_given_test_label_stage2_sub1.py 19
python3 submission_ensemble_given_test_label_stage2_sub1.py 20
python3 submission_ensemble_given_test_label_stage2_sub1.py 21
python3 submission_ensemble_given_test_label_stage2_sub1.py 22
python3 submission_ensemble_given_test_label_stage2_sub1.py 23
python3 submission_ensemble_given_test_label_stage2_sub1.py 24
python3 submission_ensemble_given_test_label_stage2_sub1.py 25
python3 submission_ensemble_given_test_label_stage2_sub1.py 26
python3 submission_ensemble_given_test_label_stage2_sub1.py 27
python3 submission_ensemble_given_test_label_stage2_sub1.py 28
python3 submission_ensemble_given_test_label_stage2_sub1.py 29
python3 submission_ensemble_given_test_label_stage2_sub1.py 30
